### ISSUE TITLE
Need help about BTXT and Font on Metroid Dread Nintendo Switch.

### ISSUE THREAD

**Issue by JokerDKha** [TeamPBCN/Metroid-Dread#1]
Need help to translation Metroid Dread on Nintendo Switch.
File almost like the 3ds version.
Tks for about helping out.
[Sample.zip](https://github.com/TeamPBCN/Metroid-Samus-Returns/files/7282387/Sample.zip).

**Comment by JokerDKha** [comment]
Text BTXT working perfect. Are font using same method on font 3ds?

**Comment by LITTOMA** [comment]
Fonts in dread is different from samus returns. Good news is we've finished the reverse engineering. It would take some time to coding.

**Comment by LITTOMA** [comment]
Added font tools. You can find font_example.bat for reference.

**Comment by JokerDKha** [comment]
@LITTOMA tks but what path and font i need to put in what folder ?
I need a guid path for that.

**Comment by JokerDKha** [comment]
Update Error
![image](https://user-images.githubusercontent.com/56380626/137078182-03e265a6-8188-4dab-8a56-77ee252f760a.png)
![image](https://user-images.githubusercontent.com/56380626/137078218-bf051d69-854e-46a0-bbb2-8acaa9aaf2c6.png)

**Comment by LITTOMA** [comment]
## Generating font tables and texture
To generate a font you should use `tools/scripts/font.py`. 

Here are the options:

* `--ttf-path`: The **input** TrueType font file (*.ttf).
* `--charset-path`: The **input** charset file. It should be a plain text file in UTF-16 encoding that containing the characters you want to put into the generated font. This means you can set it to the translated text file.
*  `--gtbl-path`: The **output** \*_glyphtable.buct file. You can find this kind of file under `romfs/system/fonts/symbols`. And you should put the generated buct file under this folder.
* `--bfnt-path-fmt`: The **output** \*.bfont file path format. The `{}` in this parameter will be replaced to the font sizes you specified.
* `--mtxt-path`: The **output** \*.bctex file. Aka the font texture file. At this time `.bctex` in the parameter will be replaced to `.png`. So you would find a *.png file instead of *.bctex after generated. We'll import the png file to a bctex file in the next step.
* `--mtxt-width`, `--mtxt-height`: The font texture width and height. These should be the same as the original texture file. You can use `tools/bin/mtxttool` to export the original texture file and check its size.
* `--gtbl-path-ingame`: Path to the generated *.buct file in romfs.
* `--mtxt-path-ingame`: Path to the generated *.bctex file in romfs.
* `--<decimal number>` options: To specify the output font sizes and their character filters. We found that the game only use font size at 32 and 52 points. 20 and 32b seem to be useless. So basically you just specify `--32 <filter for font size 32>` and `--52 <filter for font size 52>`. The filter files are also plain text files in UTF-16 encoding.
* `--<decimal number>-ttf`: The **input** TrueType font file for a font size. You can use different font styles for different sizes by specifying this parameter. If omitted, all font sizes will use what `--ttf-path` specified.
* ``--32-useicon`: Add this parameter anyway.

Here's the complete command:
`python3 .\tools\scripts\font.py create --ttf-path ".\temp\a.ttf" --charset-path ".\temp\simplified_chinese.txt" --gtbl-path ".\temp\chc_glyphtable.buct" --bfnt-path-fmt ".\temp\chc_{}.bfont" --mtxt-path ".\temp\chc_atlas.bctex" --mtxt-width 4096 --mtxt-height 2048 --gtbl-path-ingame "system/fonts/symbols/chc_glyphtable.buct" --mtxt-path-ingame "system/fonts/textures/chc_atlas.bctex" --32 .\temp\simplified_chinese.txt --32-useicon --52 .\temp\simplified_chinese.txt --52-ttf ".\temp\b.ttf"`

To run this command, you need to prepare:
* A temporary folder: `temp`
* A charset file: `.\temp\simplified_chinese.txt`. You can export a text file from BTXT for testing this example.
* Two TrueType font files: `.\temp\a.ttf` and `.\temp\b.ttf`.
* Two filter files: Which are the same as the charset file in this example.

### That's all! 

By running this command you will have `.\temp\chc_glyphtable.buct`, `.\temp\chc_32.bfont`, `.\temp\chc_52.bfont`, `.\temp\chc_atlas.png` in the temporary folder.



## Importing font texture
We'll import the generated font texture to the original `chc_atlas.bctex`

The command:
`.\tools\bin\mtxttool.exe -ig .\temp\chc_atlas.png -t .\temp\chc_atlas.bctex .\temp\origin\Romfs\textures\system\fonts\textures\chc_atlas.bctex`

Before running you should extract the original romfs folder and put it into `.\temp\origin`.

This will import `.\temp\chc_atlas.png` to the original `.\temp\orign\Romfs\textures\system\fonts\textures\chc_atlas.bctex` and write the output to `.\temp\chc_atlas.bctex`



## Making a layeredFS patch
Run the following commands to make a patch which can be used in Atmosphere.
``` batch
set FONTDIR=temp\010093801237C000\romfs\system\fonts
set SYMDIR=%FONTDIR%\symbols
set TEXDIR=temp\010093801237C000\romfs\textures\system\fonts\textures
md %SYMDIR%
md %TEXDIR%

move ".\temp\chc_glyphtable.buct" %SYMDIR%
move ".\temp\chc_*.bfont" %FONTDIR%
move ".\temp\chc_atlas.bctex" %TEXDIR%
```

### Or, just run `font_example.bat` when you prepare all files mentioned above :)



## Testing
After doing all these, you can copy `temp\010093801237C000` to `sdcard:\atmosphere\contents\` and change the game language to Simplified Chinese to see if the font changed to what your TTF file looks like!

You can use Atmosphere's [Language Override](https://www.reddit.com/r/SwitchHacks/comments/g7lvl2/atmosphere_pergame_language_override_redirection/) to change the game's default language.

**Comment by JokerDKha** [comment]
@LITTOMA tks you so much for the guide, but im still got this error.
Im using font_example.bat
![image](https://user-images.githubusercontent.com/56380626/137244285-025d903a-e68b-4da7-9792-5463bc2e1764.png)
my temp file.
![image](https://user-images.githubusercontent.com/56380626/137244301-9ffd4b95-5f06-437a-9dd0-02962a899ed6.png)

**Comment by LITTOMA** [comment]
@JokerDKha  can you upload your ttf file?

**Comment by JokerDKha** [comment]
@LITTOMA 
[font.zip](https://github.com/TeamPBCN/Metroid-Dread/files/7342734/font.zip)

**Comment by LITTOMA** [comment]
![Snipaste_2021-10-14_11-31-47](https://user-images.githubusercontent.com/10324313/137247011-3c8485b9-4c76-4e5a-92da-e99c735c563e.png)
You have 2 ".ttf" in your file names. Remove 1 of them should work.

**Comment by LITTOMA** [comment]
Note that a dependency pip package should be installed from GitHub:
`python3 -m pip install git+https://github.com/ssbothwell/greedypacker.git`

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/137247934-dab20542-60d9-4442-9712-e4dba7f1d44a.png)
greedypacker.git i cant install it on python 3

**Comment by JokerDKha** [comment]
Now im got this after pip install greedypacker 0.4
![image](https://user-images.githubusercontent.com/56380626/137248782-d3cf5ede-3ea9-493d-8105-60cdcd525161.png)

**Comment by LITTOMA** [comment]
You can download zip file from greedypacker's master branch and use pip to install the zip file.

`pip install "path/to/greedypacker-master.zip"`

**Comment by JokerDKha** [comment]
@LITTOMA  Update still got error:
![image](https://user-images.githubusercontent.com/56380626/137250304-a883a034-1306-411b-877c-bf1a0f80a30f.png)

**Comment by LITTOMA** [comment]
Please check your greedypacker version
`pip list`

This is an error in 0.4. After installing the zip file, the version should be 0.4.1.

**Comment by LITTOMA** [comment]
Please check your greedypacker version
`pip list`

This is an error in 0.4. After installing the zip file, the version should be 0.4.1.

**Comment by JokerDKha** [comment]
Tks you so much, any thing is working now.
![image](https://user-images.githubusercontent.com/56380626/137251471-6a185195-69df-4b95-8700-63fa366c8fd3.png)

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/137253436-18a8f7ed-d46e-4472-a93c-3bcb352d0397.png)
Testing in game got this error.
Edit: im know what wrong.
im try use on english text, this only working simple-chinese.
Any way can we do any thing on english text and font english?

**Comment by JokerDKha** [comment]
Update some icon error like this
![image](https://user-images.githubusercontent.com/56380626/137254360-a14134aa-dc19-42de-85a7-025096061404.png)
![image](https://user-images.githubusercontent.com/56380626/137254418-d031a676-4dfc-40ba-ae0f-5a93d2d384ef.png)

**Comment by LITTOMA** [comment]
Are there any *.bctex file in `temp\010093801237C000\romfs\textures\system\fonts\textures`?

**Comment by JokerDKha** [comment]
yeah it have this is romfs im make.
[romfs.zip](https://github.com/TeamPBCN/Metroid-Dread/files/7343189/romfs.zip)

**Comment by LITTOMA** [comment]
What language do you set in yuzu's emulation settings?

**Comment by JokerDKha** [comment]
@LITTOMA is this right?
![image](https://user-images.githubusercontent.com/56380626/137258828-c2342343-5519-47b6-bbef-000333b0e418.png)

**Comment by LITTOMA** [comment]
This is right. Your generated files also seem good. It looks like an emulator issue. Because the game language didn't change to Chinese...

**Comment by JokerDKha** [comment]
@LITTOMA  after using simplified_chinese.txt , is working. But using on english text is will make error icon.
i think font not working on english txt.
Also my font not support chinese font.
![image](https://user-images.githubusercontent.com/56380626/137267101-52e69e17-53bd-4299-bd85-5137be7acc3c.png)

**Comment by LITTOMA** [comment]
You can rename the generated file to the english file name. 

`chc_32.bfont` -> `eng_32.bfont`
`chc_glyphtable.buct` -> `eng_glyphtable.buct`
`chc_atlas.bctex` -> `eng_atlas.bctex`

etc.

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/137271645-c6f05883-ab7d-4b63-8b50-1166d1a268e9.png)
i cant find any eng font in original... i dont think rename like:
chc_32.bfont -> eng_32.bfont
chc_glyphtable.buct -> eng_glyphtable.buct
chc_atlas.bctex -> eng_atlas.bctex

will working.

**Comment by LITTOMA** [comment]
Can you find anything else relative to us_english? I don't have the extracted romfs at this time.

**Comment by JokerDKha** [comment]
[us_english.zip](https://github.com/TeamPBCN/Metroid-Dread/files/7344607/us_english.zip)
This is a font and us text. i think?

**Comment by LITTOMA** [comment]
try to add `--20 <path/to/utf16_charset.txt>` and  `--42 <path/to/utf16_charset.txt>` to the font generation script. These 2 sizes of fonts could be used by english text.

**Comment by JokerDKha** [comment]
Still got error with font us_english after using --20 <path/to/utf16_charset.txt> --42 <path/to/utf16_charset.txt>
![image](https://user-images.githubusercontent.com/56380626/137305219-0b68b406-5eec-413f-a28e-caff12fd1596.png)
[romfs.zip](https://github.com/TeamPBCN/Metroid-Dread/files/7345447/romfs.zip)

**Comment by rewold** [comment]
How to export btxt file? I tried "python btxt.py -xb romfs\system\localization\us_english.txt -p export.txt" but failed. Could you help me?

**Comment by LITTOMA** [comment]
@rewold you can fire a new issue. post your console outputs in the new issue.

**Comment by LITTOMA** [comment]
@JokerDKha  I tested us_english font without problem. You can try to add `--20-useicon` and `--42-useicon` to the command line.

**Comment by rewold** [comment]
@LITTOMA I did it! If I have a issue with import, I'll open a issue.

**Comment by JokerDKha** [comment]
@LITTOMA  Update .bat for font us, still need for simplified_chinese but it now working.
occ_20 (use for number) 32 and 52 (use for a text) and i dont know 40 use for.
Us_font.bat: (after use rename all chc to occ)
python3 .\tools\scripts\font.py create --ttf-path ".\temp\a.ttf" --charset-path ".\temp\simplified_chinese.txt" --gtbl-path ".\temp\chc_glyphtable.buct" --bfnt-path-fmt ".\temp\chc_{}.bfont" --mtxt-path ".\temp\chc_atlas.bctex" --mtxt-width 4096 --mtxt-height 2048 --gtbl-path-ingame "system/fonts/symbols/chc_glyphtable.buct" --mtxt-path-ingame "system/fonts/textures/chc_atlas.bctex" --32 .\temp\simplified_chinese.txt --32-useicon --20 .\temp\simplified_chinese.txt --20-useicon --40 .\temp\simplified_chinese.txt --52 .\temp\simplified_chinese.txt --52-ttf ".\temp\b.ttf"
.\tools\bin\mtxttool.exe -ig .\temp\chc_atlas.png -t .\temp\chc_atlas.bctex .\temp\origin\Romfs\textures\system\fonts\textures\chc_atlas.bctex

set FONTDIR=temp\010093801237C000\romfs\system\fonts
set SYMDIR=%FONTDIR%\symbols
set TEXDIR=temp\010093801237C000\romfs\textures\system\fonts\textures
md %SYMDIR%
md %TEXDIR%

move ".\temp\chc_glyphtable.buct" %SYMDIR%
move ".\temp\chc_*.bfont" %FONTDIR%
move ".\temp\chc_atlas.bctex" %TEXDIR%

**Comment by JokerDKha** [comment]
New Update working fine on us_english txt and occ font.
<3 tks you for hard working.
![unknown](https://user-images.githubusercontent.com/56380626/138394103-530c553a-1fc4-4c6c-8fec-07414f96ca1c.png)
